### ISSUE TITLE
'N' has no terrain, furniture, or other definition

### ISSUE THREAD

**Issue by linonetwo** [Kenan2000/BL9#7]
In Cataclysm-DDA experimental build #11306 MacOS Tiles

```
 DEBUG    : (json-error)
Json error: data/mods//BL9-100%-CN//Locations/Island_part1.json:2,448:21: format: rows: row 9 column 12: 'N' has no terrain, furniture, or other definition

        "%%%%.slc.%%nW....WmmW..%",
        "%%%%s.t.l%%mW....WnnW..%",
        "%%%%s...c%%N
                    ^
                     W..t.WmmW..%",
        "%%%%s...l%%%%....%%%%..%",
        "%%t.........%....%%..t.%",


 FUNCTION : bool mapgen_function_json_base::setup_common(const JsonObject &)
 FILE     : src/mapgen.cpp
 LINE     : 2523
```

**Comment by linonetwo** [comment]
This only occurs when upgrade from 11295 to 11306

**Comment by Kenan2000** [comment]
Fixed in the latest update :-) https://github.com/Kenan2000/BL9/commit/fe8dfff67e94216219dbbb0e65efafeca1b998bb

**Comment by linonetwo** [comment]
Hi, I still have some of this kind of errors in 11311 and 11306

```
 DEBUG    : (json-error)
Json error: /Users/linonetwo/Library/Application Support/Cataclysm/mods//Arcana_CN/overmap_and_mapgen/mapgen_basements.json:356:21: format: rows: row 21 column 12: 'P' has no terrain, furniture, or other definition

        "    |.p.p..b..p.p.|     ",
        "    |.p.p.....p.p.|     ",
        "    |......P
                    ^
                     ......|     ",
        "    ---------------     ",
        "                        ",


 FUNCTION : bool mapgen_function_json_base::setup_common(const JsonObject &)
 FILE     : src/mapgen.cpp
 LINE     : 2523
```

```
 DEBUG    : (json-error)
Json error: /Users/linonetwo/Library/Application Support/Cataclysm/mods//Arcana_CN/overmap_and_mapgen/mapgen_variants.json:3,056:23: format: rows: row 10 column 14: 's' has no terrain, furniture, or other definition

        "%|_______-b   -O      |.",
        ".|[_____g-   t-F      |%",
        ".|cc____g-   s
                      ^
                       -S      w%",
        ".|cc_____--+---C      w%",
        ".|---+----    -   hh  |%",


 FUNCTION : bool mapgen_function_json_base::setup_common(const JsonObject &)
 FILE     : src/mapgen.cpp
 LINE     : 2523
```

**Comment by Kenan2000** [comment]
@linonetwo Considering that Chaosvolt is the owner of the aforementioned mods - I will tell him about these after New Year's Eve - I want everyone to properly rest and have a really nice New Year's Eve celebration :-)

**Comment by linonetwo** [comment]
Oh！I didn't see this is from Arcana! Sorry for that~

Happy new Year() then! Kernan
